groups:
  - name: forge.api
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5..",job="forge-backend"}[5m]))
            /
            sum(rate(http_requests_total{job="forge-backend"}[5m]))
          ) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High API error rate (> 5%)"
          description: "Error rate is {{ $value | humanizePercentage }} over the last 5m"
          runbook_url: "https://docs.forge.internal/runbook#high-error-rate"

      - alert: HighLatencyP99
        expr: |
          histogram_quantile(0.99,
            sum(rate(http_request_duration_seconds_bucket{job="forge-backend"}[5m])) by (le)
          ) > 2.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "P99 latency > 2s"
          description: "P99 latency is {{ $value }}s"

      - alert: APIDown
        expr: up{job="forge-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Forge API is down"
          description: "No backend pods responding to scrapes"
          runbook_url: "https://docs.forge.internal/runbook#api-down"

  - name: forge.pipelines
    interval: 60s
    rules:
      - alert: PipelineFailureRate
        expr: |
          (
            sum(increase(forge_pipeline_completed_total{status="failed"}[1h]))
            /
            sum(increase(forge_pipeline_completed_total[1h]))
          ) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pipeline failure rate > 20% in last hour"
          description: "{{ $value | humanizePercentage }} of pipelines failing"

      - alert: AgentTimeout
        expr: increase(forge_agent_timeouts_total[15m]) > 3
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Multiple agent timeouts detected"
          description: "{{ $value }} agent timeouts in last 15m"

      - alert: ApprovalQueueBacklog
        expr: forge_pending_approvals > 20
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Approval queue backlog > 20"
          description: "{{ $value }} approvals waiting for over 30 minutes"

  - name: forge.infrastructure
    interval: 30s
    rules:
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          (forge_db_pool_used / forge_db_pool_size) > 0.9
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "DB connection pool > 90% utilised"
          description: "Pool at {{ $value | humanizePercentage }}"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory > 85%"
          description: "Redis at {{ $value | humanizePercentage }} capacity"

      - alert: KafkaConsumerLag
        expr: kafka_consumer_group_lag{group="forge-workers"} > 5000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Kafka consumer lag > 5000"
          description: "Consumer group forge-workers is {{ $value }} messages behind"

      - alert: PodCrashLooping
        expr: |
          increase(kube_pod_container_status_restarts_total{namespace="forge"}[15m]) > 3
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.pod }} crash looping"
          description: "{{ $value }} restarts in 15 minutes"

  - name: forge.slo
    interval: 5m
    rules:
      - record: forge:availability:30d
        expr: |
          avg_over_time(up{job="forge-backend"}[30d])

      - alert: SLOBreach
        expr: forge:availability:30d < 0.999
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "30-day availability SLO breach (< 99.9%)"
          description: "Current availability: {{ $value | humanizePercentage }}"
